### PR TITLE
Fix #134: Improve support without mbstring

### LINKED ISSUE #134: Is it supposed to work on configurations without mbstring module installed?
I saw the mention in description that it uses the polyfill when the module is not installed, however seems that it's not sufficient?

`Fatal error: Uncaught Error: Call to undefined function mb_regex_encoding()`

The product that uses Stringy is supposed to be distributed to users that may be unable to install the mbstring module.

Tested on php PHP 7.0.4-6+deb.sury.org~trusty+3

### PR DESCRIPTION
**Pull request by danielstjules**
WIP. This will be a hacky solution once I get it working, then a following major release will deprecate all use of mb_ereg. It's confusing to most anyway, since they're used to PCRE

### CODE REVIEW

File: src/Stringy.php [hunk 1]
```diff
@@ -1795,12 +1806,55 @@ private function applyPadding($left = 0, $right = 0, $padStr = ' ')
...
+    }
+
+    private function supportsEncoding()
+    {
+        $supported = array('UTF-8' => true, 'ASCII' => true);
+
+        if (isset($supported[$this->encoding])) {
+            return true;
+        } else {
+            throw new \Exception('Stringy method requires the mbstring ' .
```
Comment (GrahamCampbell) [inline src/Stringy.php]: Maybe we need RuntimeExpception?

**Comment by danielstjules** [comment]
This is a temporary solution. Deprecating use of mb_ereg in another branch which will become Stringy 3.x.
